#!/usr/bin/env bun

// Build a minimal opencode server executable for Makabaka Engine distribution.
// Uses serve-entry.ts (no yargs/y18n) to avoid Bun virtual filesystem crashes.

import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"

// Fetch and generate models.dev snapshot (skip if already exists)
const snapshotPath = path.join(dir, "src/provider/models-snapshot.ts")
if (!fs.existsSync(snapshotPath)) {
  const modelsData = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : await fetch(`https://models.dev/api.json`).then((x) => x.text())
  await Bun.write(
    snapshotPath,
    `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  console.log("Generated models-snapshot.ts")
} else {
  console.log("Using existing models-snapshot.ts")
}

const name = `opencode-makabaka-windows-x64`
console.log(`building ${name}`)

const distDir = path.join(dir, "dist", name)
await $`rm -rf ${distDir}`
await $`mkdir -p ${distDir}/bin`

// Install platform-specific native deps
await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`

// Build from serve-entry.ts — no yargs, no y18n, no TUI
await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  sourcemap: "external",
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    //@ts-ignore
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    target: "bun-windows-x64" as any,
    outfile: `dist/${name}/bin/opencode`,
    execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
    windows: {},
  },
  entrypoints: ["./src/serve-entry.ts"],
  define: {
    OPENCODE_VERSION: `'${Script.version}'`,
    OPENCODE_CHANNEL: `'${Script.channel}'`,
    OPENCODE_LIBC: "",
  },
})

console.log(`Built: dist/${name}/bin/opencode.exe`)
