export namespace AutoTest {
  export const INSTRUCTION = [
    "[AUTO-TEST INSTRUCTION]",
    "After you finish the requested task, automatically verify your changes by running a playtest:",
    "1. Call `godot_editor_command` with `scan_filesystem` to detect file changes",
    "2. Call `godot_test_command` with `run` to launch the game",
    "3. Wait 2-3 seconds for the game to initialize",
    "4. Call `godot_logs` to check for STARTUP errors — this is MANDATORY, do NOT skip",
    "   - If ANY `[ERROR]` or `[WARNING]` lines appear, or Debugger Summary shows error/warning count > 0:",
    "     → STOP here, follow [ERROR-FIRST RULE] below. Do NOT proceed to screenshot.",
    "5. Capture visual result:",
    "   - If the task involves animations, movement, or dynamic effects: call `godot_record` with duration_ms=3000",
    "   - Otherwise: call `godot_screenshot`",
    "6. Analyze the visual result for correctness and any issues",
    "7. Call `godot_test_command` with `stop`",
    "8. Call `godot_logs` again to check for RUNTIME errors that occurred during play — MANDATORY",
    "   - If new errors appeared since step 4, follow [ERROR-FIRST RULE]",
    "9. Report what you see — confirm success or describe problems found",
    "Do this AFTER completing the main task, not before.",
    "",
    "[ERROR-FIRST RULE]",
    "If at ANY point during testing you detect an error — eval fails, screenshot shows error dialog,",
    "`godot_logs` shows [ERROR] or [WARNING] lines, or debugger error/warning count > 0:",
    "1. IMMEDIATELY call `godot_test_command` with `stop` to halt the game",
    "2. Diagnose the root cause from the error message",
    "3. Fix the bug in the source code",
    "4. Re-run the full test cycle from step 1",
    "Do NOT continue testing or report results when errors are present — fix first, then re-test.",
    "Do NOT ignore log errors just because the screenshot looks fine — log errors indicate real bugs.",
    "",
    "[VISUAL EFFECT TEST-FIRST RULE]",
    "When the task involves a visual effect (particles, shaders, animations, UI transitions, post-processing, etc.):",
    "1. Create a dedicated test scene (res://test/test_<effect_name>.tscn) with the effect isolated",
    "2. Run ONLY the test scene (use `godot_test_command` with `run` and the test scene path) — NOT the main game",
    "3. Screenshot/record the test scene and present it to the user for feedback",
    "4. Iterate adjustments in the test scene until the user is satisfied",
    "5. Only after user approval, apply the effect to the actual game scene",
    "This ensures visual effects are verified in isolation before integration.",
    "",
    "[TEST CASE RULE]",
    "After developing a feature, create a test case document and use quick start scenes for testing:",
    "1. Determine the right quick start scene (res://test/qs_<context>.tscn).",
    "   Check existing qs scenes in res://test/ first — reuse if one already reaches the needed environment.",
    "   Only create a new qs scene if none fits. A qs scene skips menus and loads directly into a game context with default state.",
    "2. Create a test case document at res://test/test_<feature>.md with:",
    "   - Quick start scene reference",
    "   - Step-by-step sim expressions (use the EXACT APIs, node paths, and method names you just wrote)",
    "   - Expected results with specific verifiable values",
    "3. Execute the test by following the test case steps:",
    "   a. Call `godot_editor_command` with `scan_filesystem`",
    "   b. Run the qs scene: `godot_test_command` with `run` and scene=`res://test/qs_<context>.tscn`",
    "   c. Wait 2-3 seconds for initialization",
    "   d. Execute each eval step from the test case document",
    "   e. Screenshot and verify against expected results",
    "   f. Call `godot_test_command` with `stop`",
    "4. When testing an EXISTING feature (not just developed), read its test case from res://test/ first,",
    "   then follow the documented steps instead of writing new eval code from scratch.",
    "Do NOT use sim for complex scene navigation — use quick start scenes instead.",
  ].join("\n")
}
